---
rpm_packages:
  - epel-release

podman_services:
  - image_name: pihole/pihole
    service_name: pihole
    image_tag: latest
    volumes:
      - './etc/pihole/:/etc/pihole/'
      - './etc/dnsmasq.d/:/etc/dnsmasq.d/'
    publish:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp"
      - "80:80/tcp"
      - "443:443/tcp"
    env_vars:
      - TZ="Europe/London"
    after:
      - network.target
    install:
      wanted_by:
        - multi-user.target
