---
- hosts: all
  tasks:
    - name: Include variables depending on OS / Linux distribution
      include_vars: "{{ item }}"
      with_first_found:
        - files: ["os_{{ ansible_facts['os_family'] }}.yml"]
          skip: true
          errors: ignore
    - name: Include variables depending on OS family
      include_vars: "{{ item }}"
      with_first_found:
        - files: ["family_{{ ansible_facts['os_family'] }}.yml"]
          skip: true
          errors: ignore
    - name: Load secrets if available
      include_vars: "{{ item }}"
      with_first_found:
        - files: ["secrets.yml"]
          skip: true
          errors: ignore
    - name: Load terraform if available
      include_vars: "{{ item }}"
      with_first_found:
        - files: ["terraform.yml"]
          skip: true
          errors: ignore
    - include_role:
        name: chasinglogic.os_packages

- hosts: galactica
  become: true
  become_user: root
  roles:
    - chasinglogic.ansible_users
    - chasinglogic.docker_services
  pre_tasks:
    - name: Add docker signing key
      become: true
      become_user: root
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        keyring: /etc/apt/trusted.gpg.d/docker.gpg
    - name: Add docker repository
      become: true
      become_user: root
      apt_repository:
        repo: |
          deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
        state: present
        filename: docker
    - name: Install docker
      become: true
      become_user: root
      apt:
        update_cache: yes
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io

- hosts: kube-workers
  become: true
  become_user: root
  roles:
    # - chasinglogic.ansible_users
    # - kube-worker
